#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 05, 2019 11:25:31 AM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Gui_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    Gui_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1920x1017+-9+151")
        top.title("robot control")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.btn_einsortieren = tk.Button(top)
        self.btn_einsortieren.place(relx=0.042, rely=0.324, height=244
                , width=437)
        self.btn_einsortieren.configure(activebackground="#ececec")
        self.btn_einsortieren.configure(activeforeground="#000000")
        self.btn_einsortieren.configure(background="#00ff00")
        self.btn_einsortieren.configure(disabledforeground="#a3a3a3")
        self.btn_einsortieren.configure(font="-family {Segoe UI} -size 48")
        self.btn_einsortieren.configure(foreground="#000000")
        self.btn_einsortieren.configure(highlightbackground="#d9d9d9")
        self.btn_einsortieren.configure(highlightcolor="black")
        self.btn_einsortieren.configure(pady="0")
        self.btn_einsortieren.configure(text='''einsortieren''')

        self.btn_aussortieren = tk.Button(top)
        self.btn_aussortieren.place(relx=0.729, rely=0.324, height=244
                , width=437)
        self.btn_aussortieren.configure(activebackground="#ececec")
        self.btn_aussortieren.configure(activeforeground="#000000")
        self.btn_aussortieren.configure(background="#ff0000")
        self.btn_aussortieren.configure(disabledforeground="#a3a3a3")
        self.btn_aussortieren.configure(font="-family {Segoe UI} -size 48")
        self.btn_aussortieren.configure(foreground="#000000")
        self.btn_aussortieren.configure(highlightbackground="#d9d9d9")
        self.btn_aussortieren.configure(highlightcolor="black")
        self.btn_aussortieren.configure(pady="0")
        self.btn_aussortieren.configure(text='''aussortieren''')

        self.text_output = tk.Label(top)
        self.text_output.place(relx=0.271, rely=0.619, height=211, width=874)
        self.text_output.configure(activebackground="#f9f9f9")
        self.text_output.configure(activeforeground="black")
        self.text_output.configure(anchor='nw')
        self.text_output.configure(background="#ffffff")
        self.text_output.configure(disabledforeground="#a3a3a3")
        self.text_output.configure(font="-family {Consolas} -size 9")
        self.text_output.configure(foreground="#000000")
        self.text_output.configure(highlightbackground="#d9d9d9")
        self.text_output.configure(highlightcolor="black")
        self.text_output.configure(text='''only a test''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.271, rely=0.206, height=371, width=854)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,"./DatenDenker.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        self.Label1.configure(text='''Label''')

if __name__ == '__main__':
    vp_start_gui()





